observability:
  opentelemetry:
    file:
      path: "./otel-collector-config.txt"
    apmplus:
      endpoint: "http://apmplus-cn-beijing.volces.com:4317"
      api_key: ""
      service_name: "adk.go.test"